[package]
name = "gdrapier3d"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rapier3d = { version = "*", features = [ "enhanced-determinism" ] }
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = ["serde"] }
anyhow = "1.0.80"
